name: Trigger auto deployment for power-assert-playground

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'Playground/**'
    - '.github/workflows/power-assert-playground-AutoDeployTrigger-0200c39d-5589-4dcd-bbfe-af104bba0e65.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.POWERASSERTPLAYGROUND_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/Playground 
          registryUrl: swiftfiddle.azurecr.io
          registryUsername: ${{ secrets.POWERASSERTPLAYGROUND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.POWERASSERTPLAYGROUND_REGISTRY_PASSWORD }}
          containerAppName: power-assert-playground
          resourceGroup: swiftfiddle
          imageToBuild: swiftfiddle.azurecr.io/power-assert-playground:${{ github.sha }}
          dockerfilePath: Dockerfile

     

